[project]
name = "django-dennis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.1.1",
    "djlint>=1.35.2",
]
