# Generated by Django 5.1.1 on 2024-09-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_vote_ratio_project_vote_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[("up", "Up Vote"), ("down", "Down Vote")], max_length=200
            ),
        ),
    ]
